"""create_new_tables_for_transactions

Revision ID: 601a8f52c41e
Revises: 2f79a2faab97
Create Date: 2026-04-02 20:05:44.998569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a8f52c41e'
down_revision: Union[str, Sequence[str], None] = '2f79a2faab97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('store_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('city_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('paid_by', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('paid_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['paid_to'], ['id'])
    op.create_foreign_key(None, 'transactions', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['paid_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'paid_to')
    op.drop_column('transactions', 'paid_by')
    op.drop_column('transactions', 'city_id')
    op.drop_column('transactions', 'subcategory_id')
    op.drop_column('transactions', 'store_id')
    op.drop_table('items')
    op.drop_table('subcategories')
    op.drop_table('stores')
    op.drop_table('cities')
    # ### end Alembic commands ###
