"""update stores and subcategories relationship for many-to-many


Revision ID: 832b08d91ce1
Revises: a61c254b895f
Create Date: 2026-04-07 22:29:28.721973


"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '832b08d91ce1'
down_revision: Union[str, Sequence[str], None] = 'a61c254b895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'store_subcategories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('store_id', sa.UUID(), nullable=False),
        sa.Column('subcategory_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('store_id', 'subcategory_id', name='uq_store_subcategories_store_subcategory')
    )

    op.execute("""
        INSERT INTO store_subcategories (id, store_id, subcategory_id, created_at)
        SELECT id, store_id, subcategory_id, created_at
        FROM store_category_defaults
    """)

    op.drop_table('store_category_defaults')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'store_category_defaults',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('subcategory_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['store_id'],
            ['stores.id'],
            name=op.f('store_category_defaults_store_id_fkey'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['subcategory_id'],
            ['subcategories.id'],
            name=op.f('store_category_defaults_subcategory_id_fkey'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('store_category_defaults_pkey')),
        sa.UniqueConstraint(
            'store_id',
            name=op.f('uq_store_category_defaults_store_id'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False
        )
    )

    op.execute("""
        INSERT INTO store_category_defaults (id, store_id, subcategory_id, created_at)
        SELECT DISTINCT ON (store_id)
            id, store_id, subcategory_id, created_at
        FROM store_subcategories
        ORDER BY store_id, created_at ASC, id ASC
    """)

    op.drop_table('store_subcategories')
    # ### end Alembic commands ###