"""add_payment_to_transactions


Revision ID: a3b59901f338
Revises: 601a8f52c41e
Create Date: 2026-04-02 20:58:20.161208


"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a3b59901f338'
down_revision: Union[str, Sequence[str], None] = '601a8f52c41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


payment_method_enum = postgresql.ENUM(
    'cash', 'debit', 'credit', 'transfer',
    name='payment_method',
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    payment_method_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transactions',
        sa.Column(
            'payment_method',
            payment_method_enum,
            nullable=False,
            server_default='cash'
        )
    )
    op.alter_column(
        'transactions',
        'payment_method',
        server_default=None
    )
    op.execute("ALTER TYPE transactiontype RENAME TO transaction_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transaction_type RENAME TO transactiontype")
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###

    bind = op.get_bind()
    payment_method_enum.drop(bind, checkfirst=True)