"""update stores and create store_category_defaults

Revision ID: a61c254b895f
Revises: a3b59901f338
Create Date: 2026-04-07 07:56:11.226690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a61c254b895f'
down_revision: Union[str, Sequence[str], None] = 'a3b59901f338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


store_type_enum = postgresql.ENUM(
    'physical',
    'online',
    'subscription',
    'service',
    name='store_type',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    store_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'store_category_defaults',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('store_id', sa.UUID(), nullable=False),
        sa.Column('subcategory_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('store_id', name='uq_store_category_defaults_store_id')
    )

    op.add_column(
        'stores',
        sa.Column('type', store_type_enum, nullable=True)
    )
    op.add_column('stores', sa.Column('website', sa.String(length=200), nullable=True))

    op.execute("UPDATE stores SET type = 'physical' WHERE type IS NULL")

    op.alter_column('stores', 'type', nullable=False)

    op.drop_column('stores', 'updated_at')
    op.drop_column('stores', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stores',
        sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=True)
    )
    op.add_column(
        'stores',
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )

    op.drop_column('stores', 'website')
    op.drop_column('stores', 'type')
    op.drop_table('store_category_defaults')

    store_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###