"""update items

Revision ID: b02a4cab1311
Revises: 832b08d91ce1
Create Date: 2026-04-08 12:31:08.955165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02a4cab1311'
down_revision: Union[str, Sequence[str], None] = '832b08d91ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_items_subcategory_id_subcategories',
        'items',
        'subcategories',
        ['subcategory_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_items_subcategory_id_subcategories', 'items', type_='foreignkey')
    op.drop_column('items', 'subcategory_id')
    # ### end Alembic commands ###