"""all entities refactorized

Revision ID: d9baa4adda95
Revises: b02a4cab1311
Create Date: 2026-04-09 08:06:13.121447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9baa4adda95'
down_revision: Union[str, Sequence[str], None] = 'b02a4cab1311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # rename existing enums instead of creating new ones
    op.execute("ALTER TYPE accounttype RENAME TO account_type")
    op.execute("ALTER TYPE categorytype RENAME TO category_type")
    op.execute("ALTER TYPE userrole RENAME TO user_type")
    op.execute("ALTER TYPE userstatus RENAME TO user_status")

    # account_owners
    op.add_column(
        "account_owners",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("account_owners", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "account_owners",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("account_owners", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "account_owners", "users", ["updated_by"], ["id"])
    op.create_foreign_key(None, "account_owners", "users", ["created_by"], ["id"])
    op.alter_column(
        "account_owners",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "account_owners",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # accounts
    op.add_column(
        "accounts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("accounts", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "accounts",
        "type",
        existing_type=postgresql.ENUM("individual", "shared", name="account_type"),
        type_=sa.Enum("individual", "shared", name="account_type"),
        existing_nullable=False,
    )
    op.alter_column(
        "accounts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "accounts", "users", ["updated_by"], ["id"])
    op.alter_column(
        "accounts",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # categories
    op.add_column("categories", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "categories",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("categories", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "categories",
        "type",
        existing_type=postgresql.ENUM("income", "expense", name="category_type"),
        type_=sa.Enum("income", "expense", name="category_type"),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "categories", "users", ["updated_by"], ["id"])
    op.create_foreign_key(None, "categories", "users", ["created_by"], ["id"])
    op.alter_column(
        "categories",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # cities
    op.add_column("cities", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "cities",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("cities", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "cities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "cities", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "cities", "users", ["updated_by"], ["id"])
    op.alter_column(
        "cities",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # items (new Item catalog, no N:1 to transaction)
    op.add_column(
        "items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("items", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "items",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("items", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("items_transaction_id_fkey"), "items", type_="foreignkey")
    op.create_foreign_key(None, "items", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "items", "users", ["updated_by"], ["id"])
    op.drop_column("items", "quantity")
    op.drop_column("items", "subtotal")
    op.drop_column("items", "transaction_id")
    op.drop_column("items", "unit_price")
    op.alter_column(
        "items",
        "created_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "items",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # store_subcategories (pure pivot with composite PK)
    op.add_column("store_subcategories", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "store_subcategories",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("store_subcategories", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "store_subcategories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_constraint(
        op.f("uq_store_subcategories_store_subcategory"),
        "store_subcategories",
        type_="unique",
    )
    op.create_foreign_key(None, "store_subcategories", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "store_subcategories", "users", ["updated_by"], ["id"])
    op.drop_column("store_subcategories", "id")
    op.alter_column(
        "store_subcategories",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # stores
    op.add_column("stores", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "stores",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("stores", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "stores",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "stores", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "stores", "users", ["updated_by"], ["id"])
    op.alter_column(
        "stores",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # subcategories
    op.add_column("subcategories", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "subcategories",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("subcategories", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "subcategories",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "subcategories", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "subcategories", "users", ["updated_by"], ["id"])
    op.alter_column(
        "subcategories",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # transactions
    op.add_column(
        "transactions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("transactions", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "transactions", "users", ["updated_by"], ["id"])
    op.alter_column(
        "transactions",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )

    # users
    op.add_column("users", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.add_column("users", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "owner", "partner", name="user_type"),
        type_=sa.Enum("admin", "owner", "partner", name="user_type"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "status",
        existing_type=postgresql.ENUM("active", "pending", "inactive", "banned", name="user_status"),
        type_=sa.Enum("active", "pending", "inactive", "banned", name="user_status"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(None, "users", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "users", "users", ["updated_by"], ["id"])
    op.alter_column(
        "users",
        "updated_at",
        server_default=None,
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('active', 'pending', 'inactive', 'banned', name='user_status'),
               type_=postgresql.ENUM('active', 'inactive', 'banned', 'pending', name='userstatus'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'owner', 'partner', name='user_type'),
               type_=postgresql.ENUM('owner', 'partner', 'admin', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('transactions', 'updated_by')
    op.drop_column('transactions', 'updated_at')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.alter_column('subcategories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('subcategories', 'updated_by')
    op.drop_column('subcategories', 'updated_at')
    op.drop_column('subcategories', 'created_by')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('stores', 'updated_by')
    op.drop_column('stores', 'updated_at')
    op.drop_column('stores', 'created_by')
    op.add_column('store_subcategories', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'store_subcategories', type_='foreignkey')
    op.drop_constraint(None, 'store_subcategories', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_store_subcategories_store_subcategory'), 'store_subcategories', ['store_id', 'subcategory_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('store_subcategories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('store_subcategories', 'updated_by')
    op.drop_column('store_subcategories', 'updated_at')
    op.drop_column('store_subcategories', 'created_by')
    op.add_column('items', sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_transaction_id_fkey'), 'items', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'updated_by')
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_by')
    op.drop_column('items', 'created_at')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.alter_column('cities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('cities', 'updated_by')
    op.drop_column('cities', 'updated_at')
    op.drop_column('cities', 'created_by')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.Enum('income', 'expense', name='category_type'),
               type_=postgresql.ENUM('income', 'expense', name='categorytype'),
               existing_nullable=False)
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_by')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('accounts', 'type',
               existing_type=sa.Enum('individual', 'shared', name='account_type'),
               type_=postgresql.ENUM('individual', 'shared', name='accounttype'),
               existing_nullable=False)
    op.drop_column('accounts', 'updated_by')
    op.drop_column('accounts', 'updated_at')
    op.drop_constraint(None, 'account_owners', type_='foreignkey')
    op.drop_constraint(None, 'account_owners', type_='foreignkey')
    op.drop_column('account_owners', 'updated_by')
    op.drop_column('account_owners', 'updated_at')
    op.drop_column('account_owners', 'created_by')
    op.drop_column('account_owners', 'created_at')
    # ### end Alembic commands ###
