"""add role to users

Revision ID: eba8a983b38d
Revises: 418f6f3c2879
Create Date: 2026-03-14 15:35:14.200147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba8a983b38d'
down_revision: Union[str, Sequence[str], None] = '418f6f3c2879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: add column as nullable
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # Step 2: backfill existing rows with default value
    op.execute("UPDATE users SET role = 'partner' WHERE role IS NULL")
    
    # Step 3: now enforce NOT NULL
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
